### ISSUE TITLE
Errata en enunciado (prueba de iissue)

### ISSUE THREAD

**Issue by fermincruz** [reinaqu-fp/L01-Ejercicios-introductorios#1]
Este iissue es una tontería, pero así lo probamos.

En la siguiente frase del README.md falta una coma:

"Las preguntas son de respuesta múltiple. Lo que implica que puede haber una respuesta correcta, dos, tres, cuatro o, incluso cinco."

debería ser:

"Las preguntas son de respuesta múltiple. Lo que implica que puede haber una respuesta correcta, dos, tres, cuatro o, **incluso,** cinco."

**Comment by reinaqu-fp** [comment]
Fixed #1
